server {
    listen 80;

    # Webコンテナの静的ファイルへのアクセス設定
    location / {
        root   /usr/share/nginx/html; # Webコンテナの静的ファイルのルートディレクトリ
        index  index.html index.htm; # デフォルトのインデックスファイル
        try_files $uri $uri/ =404; # ファイルが見つからない場合は404エラーを返す
    }

    # APIへのアクセスをPython Appに転送（末尾のスラッシュでパスを調整）
    location /api/ {
        proxy_pass http://python-app:8000/; # Python Appコンテナのサービス名とポート
        proxy_set_header Host $host; # クライアントのホストヘッダーを転送
    }
}