name: 'Azure Infrastructure Build'

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  terraform-plan:
    name: '1. Terraform Plan (Test)'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: ./my-project/terraform
        run: terraform init

      - name: Terraform Plan
        working-directory: ./my-project/terraform
        env:
          TF_VAR_admin_password: ${{ secrets.TF_VAR_admin_password }}
          TF_VAR_admin_username: ${{ secrets.TF_VAR_admin_username }}
        run: terraform plan

  terraform-apply:
    name: '2. Terraform Apply & Ansible Deploy'
    needs: terraform-plan
    # ↓ この行を削除することで、featureブランチでも Ansible まで実行されます
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: ./my-project/terraform
        run: terraform init

      - name: Terraform Apply
        id: apply
        working-directory: ./my-project/terraform
        env:
          TF_VAR_admin_password: ${{ secrets.TF_VAR_admin_password }}
          TF_VAR_admin_username: ${{ secrets.TF_VAR_admin_username }}
        run: terraform apply -auto-approve

      # Ansible実行前にVMのSSHサービスが起動するのを待機
      - name: Sleep for 60 seconds
        run: sleep 60

      # TerraformのOutputからIPアドレスを取得してAnsibleに渡す
      - name: Run Ansible Playbook
        working-directory: ./my-project/Ansible
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
          ANSIBLE_PASSWORD: ${{ secrets.TF_VAR_admin_password }}
        run: |
          VM_IP=$(cd ../terraform && terraform output -raw alb_public_ip)
          
          ansible-playbook -i inventory.ini site.yml \
            -e "ansible_host=$VM_IP" \
            -e "ansible_password=$ANSIBLE_PASSWORD"